Output configure.gif

Set FontSize 16
Set Width 800
Set Height 600

Sleep 1s
Type "how --configure"
Enter
Sleep 1.5s
Down
Sleep 250ms
Down
Sleep 250ms
Sleep 1s
Enter
Sleep 1s
Down
Sleep 250ms
Down
Sleep 250ms
Sleep 1s
Enter
Sleep 1s
Type "thisisanexampleapikeyforrecordingthedemo"
Sleep 3s
Enter
Sleep 2.5s
Type "how --clear"
Sleep 1s
Enter
Sleep 1s
Down
Sleep 250ms
Down
Sleep 250ms
Type " "
Sleep 500ms
Enter
Sleep 3.5s
